version: "3.8"
services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app

  mysql-db:
    image: mysql
    restart: always
    volumes:
      - .data/db:/var/lib/mysql
    environment:
      - MYSQL_USER=gaspitas
      - MYSQL_PASSWORD=hola
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=milkstgo
    ports:
      - 33061:3306
  app:
    container_name: tingeso_pep1_1
    image: gaspitas241/tingeso_pep1
    ports:
      - "8091:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/milkstgo?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=gaspitas
      - SPRING_DATASOURCE_PASSWORD=hola
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - mysql-db


